# Generated by Django 4.2 on 2023-04-21 11:31

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.SmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_image',
            field=models.ImageField(default='', null=True, upload_to=social_media.models.get_image_file_name),
        ),
    ]
