# Generated by Django 4.2 on 2023-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0004_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
