# Generated by Django 4.2 on 2023-04-21 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_userprofile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
