# Generated by Django 4.2 on 2023-04-21 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_media", "0008_alter_userprofile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                default=[],
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
